trigger:
  branches:
    include:
      - main  # Trigger the pipeline on push to the main branch

pool:
  vmImage: 'windows-latest'  # Use Windows-based agents for the build

steps:
# Step 1: Install Java using built-in task
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'  # Specify the Java version you need

# Step 2: Set up Maven and build the project using the built-in Maven task
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your Maven pom.xml
    goals: 'clean install'    # Build the project

# Step 3: Run Selenium Tests (with Maven)
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-Dtest=**/SeleniumTests.java'  # Run specific Selenium test classes or suites
    goals: 'test'  # Run tests after building the project
